server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EgorLomachenkov/configs.git
          default-label: main
          search-paths: "{application}"
  security:
    user:
      name: config
      password: config-pass
      roles:
      - CONFIG