spring:
  application:
    name: test-app
  config:
    import: optional:configserver:http://config:config-pass@localhost:8888
  cloud:
    config:
      fail-fast: true
#      uri: http://config:config-pass@localhost:8888